# serving/system/Dockerfile.pipeline
FROM python:3.10-slim

RUN pip install --no-cache-dir \
    "ray[client,serve]==2.52.1" \
    boto3 \
    numpy \
    Pillow \
    requests \
    pyyaml

COPY pipeline.py /app/pipeline.py
COPY serve_config.yaml /app/serve_config.yaml
WORKDIR /app

CMD ["python", "pipeline.py"]
